homepage:
  # Next JS 보안문제로 인한 가장 최근의 Image pull
  image:
    repository: gethomepage/homepage
    tag: "v1.8.0"
    pullPolicy: Always

  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname:
        - home.jay-gemini.com
      paths:
        - /

  configs:
    params:
      server.insecure: true
