apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels: { { - include "homepage.labels" . | nindent 4 } }
data:
  # myvalues.yaml의 내용을 가져와서 각각의 파일로 변환합니다.
  services.yaml: |
    {{- if .Values.config.services }}
    {{- toYaml .Values.config.services | nindent 4 }}
    {{- else }}
    []
    {{- end }}

  widgets.yaml: |
    {{- if .Values.config.widgets }}
    {{- toYaml .Values.config.widgets | nindent 4 }}
    {{- else }}
    []
    {{- end }}

  settings.yaml: |
    {{- if .Values.config.settings }}
    {{- toYaml .Values.config.settings | nindent 4 }}
    {{- else }}
    {}
    {{- end }}

  bookmarks.yaml: |
    {{- if .Values.config.bookmarks }}
    {{- toYaml .Values.config.bookmarks | nindent 4 }}
    {{- else }}
    []
    {{- end }}
